# The configuration for the accountSettingsReduxFeature feature
features:
  account-settings-redux-feature:
    description: >
      This feature is for managing the roll out of the Account Settings Redux implementation
    variables:
      enabled:
        description: >
          Enables the feature
        type: Boolean
        default: false
    defaults:
      - channel: beta
        value:
          enabled: false
      - channel: developer
        value:
          enabled: false
